

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import io.github.bonigarcia.wdm.WebDriverManager;

public class TesteTradutorMVC {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tradutorTesteElevator() {
        driver.get("http://localhost:8080/TradutorMVC/");
        driver.manage().window().setSize(new Dimension(974, 1032));
        driver.findElement(By.name("palavra")).click();
        driver.findElement(By.name("palavra")).sendKeys("elevator");
        driver.findElement(By.name("submit")).click();
        driver.findElement(By.cssSelector(".h1")).click();
        assertThat(driver.findElement(By.cssSelector(".h1")).getText(), is("A tradução de elevator é elevador"));
    }

    @Test
    public void tradutorTesteYears() {
        driver.get("http://localhost:8080/TradutorMVC/");
        driver.manage().window().setSize(new Dimension(974, 1032));
        driver.findElement(By.name("palavra")).click();
        driver.findElement(By.name("palavra")).sendKeys("years");
        driver.findElement(By.name("submit")).click();
        driver.findElement(By.cssSelector(".h1")).click();
        driver.findElement(By.cssSelector(".h1")).click();
        assertThat(driver.findElement(By.cssSelector(".h1")).getText(), is("A tradução de years é anos"));
    }

    @Test
    public void tradutorTesteFalha() {
        driver.get("http://localhost:8080/TradutorMVC/");
        driver.manage().window().setSize(new Dimension(974, 1032));
        driver.findElement(By.name("palavra")).click();
        driver.findElement(By.name("palavra")).sendKeys("money");
        driver.findElement(By.name("submit")).click();
        driver.findElement(By.cssSelector(".h2")).click();
        assertThat(driver.findElement(By.cssSelector(".h2")).getText(), is("A palavra money infelizmente ainda não foi adicionada no tradutor, tente novamente em outra hora."));
    }
}
